name: Deploy Infrastructure and Configure with Ansible

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AWS_REGION: "ap-northeast-2"
  INSTANCE_TYPE: "t2.micro"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Apply
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Get EC2 Public IP
        id: get_ip
        run: |
          IP=$(terraform output -raw instance_public_ip)
          echo "EC2_PUBLIC_IP=$IP" >> $GITHUB_OUTPUT

      - name: Wait for SSH Availability
        run: |
          for i in {1..30}; do
            if nc -z -w 5 ${{ steps.get_ip.outputs.EC2_PUBLIC_IP }} 22; then
              echo "SSH is available!"
              exit 0
            fi
            sleep 10
          done
          echo "SSH connection timed out"
          exit 1

      - name: Create Ansible Inventory
        run: |
          mkdir -p ansible
          cat <<EOF > ansible/inventory.ini
          [web]
          web_server ansible_host=${{ steps.get_ip.outputs.EC2_PUBLIC_IP }} ansible_user=ubuntu

          [all:vars]
          ansible_python_interpreter=/usr/bin/python3
          ansible_ssh_private_key_file=./keys/ec2_key.pem
          EOF

      - name: Run Ansible Playbook
        run: |
          cd ansible
          ansible-playbook -i inventory.ini playbooks/deploy.yml
